[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:125 Incompatible release of msedgedriver (version 115.0.1860.0) detected in PATH: C:\Users\HP\Downloads\DRIVERS\msedgedriver.exe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015D40799BD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4f3d6be044ff790afcb6705283682d94
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015D4079B650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4f3d6be044ff790afcb6705283682d94
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015D4079B8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4f3d6be044ff790afcb6705283682d94