[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:125 Incompatible release of msedgedriver (version 115.0.1860.0) detected in PATH: C:\Users\HP\Downloads\DRIVERS\msedgedriver.exe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DCC09B61D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f2be79a0e758a4590b72d3164fa8386d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DCC09B4810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f2be79a0e758a4590b72d3164fa8386d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DCC09B5910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f2be79a0e758a4590b72d3164fa8386d